gui:
  theme:
    activeBorderColor:
      - "#FF9E64" # Neon orange for active elements
      - bold
    inactiveBorderColor:
      - "#4db0c9" # Balanced cyan-blue for inactive elements
    optionsTextColor:
      - "#4db0c9" # Matching inactive border color
    selectedLineBgColor:
      - "#4877ab" # Balanced blue for selected lines
    cherryPickedCommitBgColor:
      - "#3D99FF" # Matching selected line color
    cherryPickedCommitFgColor:
      - "#FFFFFF" # White text for contrast
    unstagedChangesColor:
      - "#FF9E64" # Neon orange for unstaged changes
  nerdFontsVersion: "3"
  border: "rounded"
  showCommandLog: true
  showBottomLine: true
  showFileTree: true
  showRandomTip: true
  showIcons: true
git:
  paging:
    colorArg: always
    useConfig: true
# os:
#   editCommand: "nvim"
#   editCommandTemplate: '{{editor}} --server \\\\.\\pipe\\nvim-server --remote-tab "{{filename}}"'
