#Include app-launchers.ahk
#Include misc.ahk
#Include chrome-windows.ahk

global LeaderCommands := Map(
  ".m", WriteMessageDontResendAllCode,
  ".n", ActivateOneNote,
  ".w", WriteMessageWorstUserName,
  "/", (*) => ReplaceSlashes("/"),
  "0", ActivateUngroupedChromeWindow,
  "1", ActivateBrowser1Window,
  "2", ActivateBrowser2Window,
  "3", ActivateBrowser3Window,
  ";f", (*) => QuickSetup(mode := "full"),
  ";s", (*) => QuickSetup(mode := "simple"),
  "\", (*) => ReplaceSlashes("\"),
  "a", activateAgeOfEmpires2,
  "A", ActivateAlacritty,
  "B", ActivateBitwarden,
  "b", ActivateBraveBrowser,
  "c", ActivateLosslessCut,
  "D", ActivateAutoDuck,
  "d", ActivateDiscord,
  "f", ActivateSreamFeedApp,
  "F", ActivateSreamFeedAppDebug,
  "g", ActivateSteam,
  "G", ActivateTobiiGhost,
  "k", ActivateKovaaks,
  "l", ActivateDeadlock,
  "m", ActivateMailClient,
  "N", ActivateNeo4j,
  "n", ActivateNeovide,
  "o", (*) => ActivateOBS(),
  "O", (*) => ActivateOBSPortable(profile := "ftp", moveChat := true),
  "P", ActivateAdminPowerShell,
  "p", ActivatePowerShell,
  "r", ActivateStreamDeck,
  "RR", Reload,
  "s", ActivateSpotify,
  "Space1", (*) => CaptureCurrentChromeWindow(1),
  "Space2", (*) => CaptureCurrentChromeWindow(2),
  "Space3", (*) => CaptureCurrentChromeWindow(3),
  "Space]", ResetChromeWindowList,
  "Spacen", ActivateNotepad,
  "T", (*) => ActivateStreamerBot(portableVersion := "ftp"),
  "t", (*) => ActivateStreamerBot(portableVersion := "production"),
  "u", ActivateOsu,
  "V", (*) => ActivateOBSPortable(profile := "vcam"),
  "v", ActivateVSCode,
  "W", (*) => ActivateWezTermTitled("WezTerm - secondary"),
  "w", ActivateWezTerm,
  "x", ActivateExplorer,
  "y", ActivatePyCharm,
)
