gui:
  theme:
    activeBorderColor:
      - "#E6D6AC"  # Light ivory for active elements
      - bold
    inactiveBorderColor:
      - "#34495E"  # Muted navy blue for inactive elements
    optionsTextColor:
      - "#E6D6AC"  # Light ivory for options text
    selectedLineBgColor:
      - "#4A6785"  # Slightly lighter navy for selected lines
    selectedRangeBgColor:
      - "#4A6785"  # Matching selected line color
    cherryPickedCommitBgColor:
      - "#5C7A99"  # Slightly brighter navy for cherry-picked commits
    cherryPickedCommitFgColor:
      - "#F0E6D2"  # Warmer ivory for contrast on cherry-picked commits
    unstagedChangesColor:
      - "#D4B483"  # Muted gold for unstaged changes
    directory:
      - "#7FA0C1"  # Lighter navy for directories
    defaultFgColor:
      - "#F0E6D2"  # Warm ivory for default text
    defaultBgColor:
      - "#1C2833"  # Dark navy background
  nerdFontsVersion: "3"
  border: "rounded"
  showCommandLog: true
  showBottomLine: true
  showFileTree: true
  showRandomTip: true
  showIcons: true
git:
  paging:
    colorArg: always
    useConfig: true
